require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CouncilDistrictsController do

  # This should return the minimal set of attributes required to create a valid
  # CouncilDistrict. As you add validations to CouncilDistrict, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CouncilDistrictsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all council_districts as @council_districts" do
      council_district = CouncilDistrict.create! valid_attributes
      get :index, {}, valid_session
      assigns(:council_districts).should eq([council_district])
    end
  end

  describe "GET show" do
    it "assigns the requested council_district as @council_district" do
      council_district = CouncilDistrict.create! valid_attributes
      get :show, {:id => council_district.to_param}, valid_session
      assigns(:council_district).should eq(council_district)
    end
  end

  describe "GET new" do
    it "assigns a new council_district as @council_district" do
      get :new, {}, valid_session
      assigns(:council_district).should be_a_new(CouncilDistrict)
    end
  end

  describe "GET edit" do
    it "assigns the requested council_district as @council_district" do
      council_district = CouncilDistrict.create! valid_attributes
      get :edit, {:id => council_district.to_param}, valid_session
      assigns(:council_district).should eq(council_district)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CouncilDistrict" do
        expect {
          post :create, {:council_district => valid_attributes}, valid_session
        }.to change(CouncilDistrict, :count).by(1)
      end

      it "assigns a newly created council_district as @council_district" do
        post :create, {:council_district => valid_attributes}, valid_session
        assigns(:council_district).should be_a(CouncilDistrict)
        assigns(:council_district).should be_persisted
      end

      it "redirects to the created council_district" do
        post :create, {:council_district => valid_attributes}, valid_session
        response.should redirect_to(CouncilDistrict.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved council_district as @council_district" do
        # Trigger the behavior that occurs when invalid params are submitted
        CouncilDistrict.any_instance.stub(:save).and_return(false)
        post :create, {:council_district => {  }}, valid_session
        assigns(:council_district).should be_a_new(CouncilDistrict)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CouncilDistrict.any_instance.stub(:save).and_return(false)
        post :create, {:council_district => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested council_district" do
        council_district = CouncilDistrict.create! valid_attributes
        # Assuming there are no other council_districts in the database, this
        # specifies that the CouncilDistrict created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CouncilDistrict.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => council_district.to_param, :council_district => { "these" => "params" }}, valid_session
      end

      it "assigns the requested council_district as @council_district" do
        council_district = CouncilDistrict.create! valid_attributes
        put :update, {:id => council_district.to_param, :council_district => valid_attributes}, valid_session
        assigns(:council_district).should eq(council_district)
      end

      it "redirects to the council_district" do
        council_district = CouncilDistrict.create! valid_attributes
        put :update, {:id => council_district.to_param, :council_district => valid_attributes}, valid_session
        response.should redirect_to(council_district)
      end
    end

    describe "with invalid params" do
      it "assigns the council_district as @council_district" do
        council_district = CouncilDistrict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CouncilDistrict.any_instance.stub(:save).and_return(false)
        put :update, {:id => council_district.to_param, :council_district => {  }}, valid_session
        assigns(:council_district).should eq(council_district)
      end

      it "re-renders the 'edit' template" do
        council_district = CouncilDistrict.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CouncilDistrict.any_instance.stub(:save).and_return(false)
        put :update, {:id => council_district.to_param, :council_district => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested council_district" do
      council_district = CouncilDistrict.create! valid_attributes
      expect {
        delete :destroy, {:id => council_district.to_param}, valid_session
      }.to change(CouncilDistrict, :count).by(-1)
    end

    it "redirects to the council_districts list" do
      council_district = CouncilDistrict.create! valid_attributes
      delete :destroy, {:id => council_district.to_param}, valid_session
      response.should redirect_to(council_districts_url)
    end
  end

end
